hostname: 192.168.95.143

ledger:
  orgs:
    org1:
      name: org1
      mspId: Org1MSP
      domname: org1.example.com
      caLocation: http://${hostname}:7054
      peers:
        - name: peer0.org1.example.com
          url: grpc://${hostname}:7051
        - name: peer1.org1.example.com
          url: grpc://${hostname}:7056
      orderers:
        - name: orderer.example.com
          url: grpc://${hostname}:7050
      eventHubs:
        - name: peer0.org1.example.com
          url: grpc://${hostname}:7053
        - name: peer1.org1.example.com
          url: grpc://${hostname}:7058
    org2:
      name: org2
      mspId: Org2MSP
      domname: org2.example.com
      caLocation: http://${hostname}:8054
      peers:
        - name: peer0.org2.example.com
          url: grpc://${hostname}:8051
        - name: peer1.org2.example.com
          url: grpc://${hostname}:8056
      orderers:
        - name: orderer.example.com
          url: grpc://${hostname}:7050
      eventHubs:
        - name: peer0.org2.example.com
          url: grpc://${hostname}:8053
        - name: peer1.org2.example.com
          url: grpc://${hostname}:8058
  userList:
    - name: admin
      secret: adminpw
    - name: user1
      secret: user1
  channelList:
    - name: foo
      path: e2e-2Orgs/channel
    - name: bar
      path: e2e-2Orgs/channel
  channelPath: e2e-2Orgs/channel
  chaincodeList:
    - name: rebare_cc
      path: demo/target/classes
      version: 1
  times:
    gossipWaitTime: 500000
    invokeWaitTime: 10000000
    deployWaitTime: 12000000
    proposalWaitTime: 12000000
  runWithTls: false
  cryptoConfigPath: crypto-config/peerOrganizations/

server:
  port: 8081
debug: false